### PR TITLE
Added Python 3.4 support

### PR DESCRIPTION
**Pull request by vincentfretin**
This is now compatible with both Python 2.7 and Python 3.4.
This uses robotframework-python3 with Python 3.

### CODE REVIEW

**Comment by vincentfretin** [comment]
With Python 2.7, I have 14 failing tests on master without my changes, same on my fork.

With Python 3.4
pip install robotframework-python3 selenium decorator docutils
python test/run_tests.py python firefox --noncritical ignore_firefox_error

I get 161 failing tests.
If somebody want to contribute to the effort, please do. I put this in standby.

**Comment by vincentfretin** [comment]
I did a complex robot test on my pyramid project with Py 3.4. In real, it works.
So it seems that the robotframework-selenium2library tests have to adapted to Py 3.4.

**Comment by shadeimi** [comment]
Sorry for the OT, what about the status of this rework for python3.4? May i contribute?

**Comment by vincentfretin** [comment]
Nothing changed since my last comment. It works but the tests fails. Help appreciated.

**Comment by emanlove** [comment]
Other than figuring out those errors, I would also like to see this tested with IronPython and Jython for which I don't suspect that Python 3.x is out. But at least it should cause issue with the currently supported versions of these Python flavors.

**Comment by zupo** [comment]
Hey any update on this? It's a real shame there is no Python 3 support in master. Can I help in some way?

**Comment by vincentfretin** [comment]
Hi zupo, you sure can help. You can start where I left of. We need the tests to pass on Python 2.7, 3.4 and apparently emanlove want it for IronPython, Jython, I don't know if we can automate this easily.

**Comment by zupo** [comment]
Yeah, that's the "problem". I have zero exp. with IronPython/Jython and have no idea even where to start. I could handle py2.7/3.4 though ...

**Comment by just-be-dev** [comment]
Jython/IronPython support should be easy to add, but that isn't a primary objective of this change. This PR is focused around Python 3, focus on that goal. 

I want to move us towards making small, incremental changes that are very focused on a particular topic.

**Comment by aaltat** [comment]
Also we must support the Python 3.x version which the core framework will support. See details #479

**Comment by tisto** [comment]
Any update on this?

**Comment by molsky** [comment]
RF 3.0 Alpha 1 is now released, so what is the situation with S2L's Python 3 support?

**Comment by andreabisello** [comment]
Not able to install under python 3.4 under windows 7

C:\Python34\Scripts>pip install robotframework-python3
Collecting robotframework-python3
  Downloading robotframework-python3-2.9.tar.gz (3.5MB)
    100% |################################| 3.5MB 114kB/s
Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in c:\python3
4\lib\site-packages (from robotframework-python3)
Installing collected packages: robotframework-python3
  Running setup.py install for robotframework-python3
Successfully installed robotframework-python3-2.9

C:\Python34\Scripts>pip install robotframework-selenium2library
Collecting robotframework-selenium2library
  Using cached robotframework-selenium2library-1.7.4.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\ANDREA~1.BIS\AppData\Local\Temp\pip-build-b9w1e5oq\robotfra
mework-selenium2library\setup.py", line 7, in <module>
        from ez_setup import use_setuptools
      File "C:\Users\ANDREA~1.BIS\AppData\Local\Temp\pip-build-b9w1e5oq\robotfra
mework-selenium2library\src\ez_setup.py", line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in C:\Users\ANDREA~1
.BIS\AppData\Local\Temp\pip-build-b9w1e5oq\robotframework-selenium2library

C:\Python34\Scripts>

**Comment by aaltat** [comment]
The Selenium2Library doesn't, yet, support Python 3, but there development going on that direction. If you want to use this pull request, you must check it out and perform installation by using the source code. More details, for the source code installation, can be found from here: https://github.com/robotframework/Selenium2Library/blob/master/INSTALL.rst

**Comment by pekkaklarck** [comment]
Yeah, Python 3 isn't yet supported. It's a real problem that the included `ez_setup.py` isn't Python 3 compatible, though. I don't think it is needed anymore and should be removed.

**Comment by andreabisello** [comment]
oh no problem for me! my mistake was created by this comment

vincentfretin commented on 2 Jun 2014
This is now compatible with both Python 2.7 and Python 3.4.

i thinked it was already in the stable release.

**Comment by aaltat** [comment]
You might be better of using the experimental release made by HelioGuilherme66: https://github.com/HelioGuilherme66/robotframework-selenium2library/releases

**Comment by aaltat** [comment]
There has been lo of changes since this PR and therefore closing the PR. But we are making the support for Python 3 and would be happy to receive small PR to support Python 3 and Python 2.7

**Pull request closed without merging**
