### PR TITLE
seleniumLibrary new commit

### LINKED ISSUE #1517: Add parameter to make Wait Until Page Contains case insensitive
It would be great to be able to turn off case sensitivity for keywords like `Element Text Should Be`, `Wait Until Element Contains`, `Wait Until Element Does Not Contain`, `Wait Until Page Contains` and `Wait Until Page Does Not Contain`

This feature was already implemented for `Element Should Contain` and `Element Should Not Contain` in #849.

I spent lots of time trying to understand why `Wait Until Page Contains` fails just to find that it is a case sensitive and case on the screen was displayed differently, because of CSS style: `text-transform: lowercase`

I would vote to make these keywords case insensitive by default and case sensitive via parameter. I think it would make tests faster to write and less brittle.

### PR DESCRIPTION
**Pull request by ritikasaboo**
Fixes #1517

### CODE REVIEW

**Comment by aaltat** [comment]
Please cleanup the PR. 
1) The robot framework output files and the geckodriver.log  should never be part of the PR.
2) The Approval tests approved files should have not been changed. 
3) There is failing[ unit test](https://travis-ci.org/robotframework/SeleniumLibrary/jobs/625811774?utm_medium=notification&utm_source=github_status).  Because of the added argument, mock does not match, please fix it.

**Comment by aaltat** [comment]
And write tests for the change.

**Comment by aaltat** [comment]
@colourmein13 do you still plan to work with the PR?

**Comment by aaltat** [comment]
Closing due inactivity. Can be reopened if there is a need.

**Comment by colourmein13** [comment]
@aaltat Hey, how can I fix the failed utest? I added an additional argument in the utest but it still fails.

**Comment by ritikasaboo** [comment]
> Closing due inactivity. Can be reopened if there is a need.

Hey. Apologies as I got busy with other stuff. 
1. Should I add .log to my .gitignore? What output files are you talking about? 
2. I haven't changed the content, but I see what you mean. 
3. I have fixed the failed unittest. Should I create new PR for the new tests?

**Comment by aaltat** [comment]
No worries, we do not have schedules and working in your own pace is always recommended. 

1) Modifications to `.gitignore` should not be needed. It looks like you do not use [atest/run.py](https://github.com/robotframework/SeleniumLibrary/blob/master/atest/run.py) to run the tests and therefore output files are not created in the already ignored folder. There is a [readme](https://github.com/robotframework/SeleniumLibrary/blob/master/atest/README.rst) file which explain in more details how running tests works out of the box. 
3) It looks like you have deleted to whole branch from you fork and therefore I can not reopen this PR. I think most easiest way is to create the new PR whit all the changed needed.

**Pull request closed without merging**
