### PR TITLE
Click Element keyword enhanced to open in new window

### PR DESCRIPTION
**Pull request by ponkar**

### CODE REVIEW

**Comment by aaltat** [comment]
I did restart the build and let's see how it goes.

But this PR git history is not correct and it can not be merged to the master.  Most likely there has been some rewrite of the history, by accident in `git merge` or `git rebase`. Most likely it's easiest to start new branch directly from the master and cherry pick your commits on top of the new branch. Do you need help with the solving the git history or are you able to solve the problem by your self?

**Comment by aaltat** [comment]
The test are executed but there is failure in on of the test cases. Could you fix it?

**Comment by ponkar** [comment]
@aaltat Please see PR #936  which I did fresh but didnt help

**Comment by aaltat** [comment]
I will close this PR on favour #936

**Pull request closed without merging**
