### PR TITLE
Added of 'Get Window Position' and 'Set Window Position' keywords

### PR DESCRIPTION
**Pull request by ktarasz**
Added 'Get Window Position' and 'Set Window Position' keywords matching the Selenium functionality.
 #366 
 #367

### CODE REVIEW

**Comment by ktarasz** [comment]
The 'Double Click Element' test case failed, but 'Get and Set Window Position' passed. Can someone help me with the failed test?

**Comment by just-be-dev** [comment]
I don't think this is actually a failure with your PR. The same thing happened with mine (#365).

**Comment by just-be-dev** [comment]
@ktarasz I somewhat traced it down. It's a known failure though it doesn't actually seem to be a problem with this library. It seems like it's an actual bug in selenium. Regardless, I've added a PR to make it a non-critical failure so you test will pass after that gets merged. (See #371)

**Comment by just-be-dev** [comment]
@ktarasz, if you'll update this I'll merge it.

**Pull request merged**
