### PR TITLE
Improve behavior of setting desired_capabilities

### PR DESCRIPTION
**Pull request by matthewvalimaki**
Remove forceful Firefox profile definition.
Add ability to remove default desired_capabilities definitions.

Signed-off-by: Matthew Valimaki matthew.valimaki@gmail.com

### CODE REVIEW

**Comment by matthewvalimaki** [comment]
A bit more background:
When Selenium node is on headless Alpine Linux Firefox would refuse to start up because of how Selenium2Library set `firefox_profile`. Selenium2Library always sets `firefox_profile` without giving me the option to not to set it. Likewise `marionette: false` was being set again giving me no way to remove it altogether. Yes, I could do `marionette: true` but that is not what I'm looking for, I want complete removal of the value.

The changes I've introduce do two things:
1) do not enforce Firefox profile. Validate the `ff_profile_dir` if defined.
2) allow removal of key-values from `desired_capabilities`

**Comment by aaltat** [comment]
Could you create an issue about the problem and describe the problem which you are trying to solve. Issue helps us to track the status of the project.

**Comment by aaltat** [comment]
As a side note, would the #552 also solve this problem?

**Comment by aaltat** [comment]
Closing due inactive.

**Pull request closed without merging**
