### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein
### GitHub Corrected URLs

| Was | Now |
| --- | --- |
| https://github.com/rtomac/robotframework-selenium2library/wiki | https://github.com/robotframework/Selenium2Library/wiki |
### Other Corrected URLs

| Was | Now |
| --- | --- |
| http://rtomac.github.com/robotframework-selenium2library/doc/Selenium2Library.html | http://rtomac.github.io/robotframework-selenium2library/doc/Selenium2Library.html |
| http://selenium.openqa.org | http://docs.seleniumhq.org |
| http://seleniumhq.org/docs/03_webdriver.html | http://docs.seleniumhq.org/docs/03_webdriver.jsp |

### CODE REVIEW

**Comment by just-be-dev** [comment]
I'm assuming @ReadmeCritic is a bot? This is good, but the rtomac link should be changed to http://robotframework.org/Selenium2Library/doc/Selenium2Library.html

**Comment by just-be-dev** [comment]
I'll go ahead an merge this then make that change in the readme.

**Comment by just-be-dev** [comment]
This was actually on a bare README. It doesn't have any effect on our main README.rst. 

@robotframework/selenium2library I merged it in, but it won't have any actual effect. Should we have both README and README.rst? Obviously the README.rst is more complete.

**Comment by dkhamsing** [comment]
Should probably only have one :smile:

**Comment by aaltat** [comment]
It is a bot and we should delete the bare README file.

**Comment by emanlove** [comment]
I **strongly** dislike random anonymous bots!!!

**Comment by dkhamsing** [comment]
Sorry for offending you.. feel free to close next time :cry:

**Comment by just-be-dev** [comment]
@dkhamsing It's all good. I appreciate what you're attempting to do. You probably should test how GitHub does README load ordering. In general I'm sure this won't happen a lot, but as it happen here it will likely happen again.

**Comment by emanlove** [comment]
@dkhamsing: It pointed out an issue, ok. But it also didn't couldn't fix other similar issues. And it is pointing out that I am lazy and haven't cleaned out old files. Maybe I am just upset at myself and taking out on a bot :) . 

Not a problem. My problem with vehicle-modification droids, sorry that should have been auto-correction bots (silly iPhone), comes from seeing bots in Wikipedia editing the talk page on article that hasn't had major updates for three years and the talk page hasn't be update by real people in five years. The question there is what is the point. Of course here you found my laziness, I'm mean feature!

I would also like it if the auto-generated bot comment above mentioned who started it and the bot kick-off mechanism allowed for you to comment on it. But you did here any ways for which I thank you. Don't let my grumpiness stop you from contributing. Thanks again.

**Comment by ReadmeCritic** [comment]
@zephraph yeah definitely gotta look into how README get loaded, thx

**Comment by ReadmeCritic** [comment]
@emanlove good points, thanks for your feedback

**Pull request merged**
