### PR TITLE
Enhance location strategy

### PR DESCRIPTION
**Pull request by divfor**
This PR will enhance 'Add Location Strategy' to support feature like page object:
1. writing meaningful text instead of locator in test case/keyword with good readability;
2. storing key (meaningful text) / value (locator) pairs in python dictionaries or external db/API;
3. locator could be nested with any number of variables from current namespace;
4. final locator will be variables-replaced automatically by the underlying of Selenium 2 Library;
5. not affecting any existing usage of locator and 'Add Location Strategy'.

Example:
## Step 1: define key / value (meaningful text / locator) pairs

here is a dictionary example. 
use variables to make good combination of xpath for good readability and modifiying-friendly structure.

``` python
all_blocks = '//form'
# ${index} to be defined in user keyword
login_block = '//${all_blocks}[@id="login"]/div[${index}]'
dict_users = { 
    'User Name': 'id=input_0', 
    'Password': 'id=input_1', 
    'Add Button': '${login_block}/div/button[1]',
    'Delete Button': '${login_block}/div/button[2]
}
```

Please noticed that  'Replace Variables' will pick up variables from the executing keyword's namespace - that means ${all_blocks} defined in python file (global) and ${index} defined in current user keyword (local) will be replaced together. When user keyword A calls user keyword B, variables defined in A will fail to be replaced in B due to B's namespace does not have them.
## Step 2: define user keyword as strategy keyword:

The strategy keyword expects arguments  ${location}, ${criteria}, and should return ${locator}.  Use 'Add Location Strategy' to register it so that all keywords can accept the custom prefix (strategy name)
for example:

``` robotframework
Get Locator By Item Prompt Text
    [Arguments] | ${mongodb} | ${criteria}
    ${locator}= | Read From Your Database | ${db} | ${criteria}
     [Return] | ${locator}
```

Register the strategy keyword with a strategy name (shorter is better):

``` robotframework
Add Location Strategy | mg | Get Locator By Item Prompt Text
```

If location is a dictionary and strategy keyword is not defined,  default dict.get() will be used:

``` robotframework
Add Location Strategy | du |  | ${dict_users}
# or
Add Location Strategy | du | location=${dict_users}
```
## Step 3: use custom prefix in test cases / keywords:

``` robotframework
***Test Cases***
    Input Text | du=User Name
    Input Password | du=Password
    ${index} = | Set Variable | 2
    Click Element | du=Add Button  #explicitly variable replaced with ${index}
```

In the teardown of keyword or test cases, unregistered the strategy name:

``` robotframework
Remove Location Strategy | mg
Remove Location Strategy | du
```

### CODE REVIEW

**Comment by divfor** [comment]
A usage scenario of this change is:
when both QA and DEV start a project, QA can start to write automation tests from requirement document even if they don't know what exact locators will be created by DEV. the element - locator mapping could be given in a later time if they has this enhancement.

**Comment by divfor** [comment]
Notes to this PR: 
1. the original 'Add Location Strategy' usage (without location argument) still works as usual.
2. All Selenium2Library keywords works well with existing locators so there is no impact on existing tests.
3. All Selenium2Library works well with custom locator (including 'Get Element Attribute'), except 'Get Matching Xpath Count'  -  it can be simply replaced by keywords 'Get Webelements' and 'Get Length'.

**Comment by divfor** [comment]
Hi all, I updated the descriptions. could you have time to review this PR? @zephraph @emanlove

**Comment by just-be-dev** [comment]
@emanlove, can you take a look? I've been away from this project for too long to feel comfortable doing a review of this.

**Comment by aaltat** [comment]
We all have been inactive for a good amount of time. If you have time and interest, just go for it.

**Comment by divfor** [comment]
Moved this to PR #680 for avoiding rebase issue.

**Pull request closed without merging**
