### PR TITLE
add jquery active wait for finding elemnet

### PR DESCRIPTION
**Pull request by jollychang**
for every element find

### CODE REVIEW

**Comment by j1z0** [comment]
I do like the idea of adding jQuey support but I have a concern with the way it is implemented in this pull request. 
The issue I have has to do with performance. I someone is not using jQuery this incurs and extra round trip for every single element find. This make a big difference in overall performance when using a remote client. 

I would rather see an option added to the library init such as UseJquery it should default to false abd only call the jQuery bits if its value is true.

**Comment by jollychang** [comment]
@j1z0 ok，I will try to add as a option

**Comment by jollychang** [comment]
update  as options from import Selenium2Library

**Comment by peritus** [comment]
I always implement this in "Robot Framework userland":

```
*** Keywords ***

Wait For Ajax
    Wait for Condition   return window.jQuery.active == 0;
```

And I think it's better kept that way.

**Comment by omahlama** [comment]
I agree with @peritus, there are cases where you want to do things without waiting for ajax, so the choice should be left to the end user. Maybe documenting this as a typical use scenario would be useful instead.

**Comment by peritus** [comment]
@omahlama Yes, documentation would be great, also could include examples for all popular Ajax wrapping frameworks!

**Comment by emanlove** [comment]
Consensus seems to be to use a Robot Framework keyword instead of suggested pull request. Added issue #175.

**Pull request closed without merging**
