### PR TITLE
Location is key

### PR DESCRIPTION
**Pull request by Caos-Maker89**
#1297 : new wait until location is key

### CODE REVIEW

**Comment by Caos-Maker89** [comment]
I put the wrong message of issue on commit.. the correct one is: 1297

**Comment by acaovilla** [comment]
@aaltat any ideas why the sanity check fails? 
thanks

**Comment by Caos-Maker89** [comment]
now it's ok :p

**Comment by aaltat** [comment]
Thank you from the PR.

Looking ok from a mobile screen, but I need to take a look from a bigger screen (mobile screen makes me blind for certain types of things.)

**Comment by aaltat** [comment]
@acaovilla there is a conflict(s) in your PR and therefore it can not be merged. Also those merge commits are not allowed. Do you need help on resolving the problem (which can be done by git commands) or can you manage by your self or do you want me to do it for you?

**Comment by Caos-Maker89** [comment]
> @acaovilla there is a conflict(s) in your PR and therefore it can not be merged. Also those merge commits are not allowed. Do you need help on resolving the problem (which can be done by git commands) or can you manage by your self or do you want me to do it for you?

I think I can manage by myself, but how and where I can view conflict on github? Because I see "This branch has no conflicts with the base branch" there.. 

thank u :)

**Comment by aaltat** [comment]
Strange, the conflict is only visible when viewing the PR in desktop view and not in mobile view. At least for me.

Well anyway that merge commit should be removed. I think easiest option is to start new branch from master, pull changes from this repository and cherry pick the commits you have made. Although that is not the only way.

**Pull request closed without merging**
