### PR TITLE
Update python build version to v3.8.0

### PR DESCRIPTION
**Pull request by chenrui333**

### CODE REVIEW

**Comment by aaltat** [comment]
Hmm, as far I know the last official Python release is 3.141.0 https://pypi.org/project/selenium/ Do you have something else in your mind?

**Comment by chenrui333** [comment]
@aaltat yeah, you are absolutely right, somehow I was seeing their release in their release page :(

https://github.com/SeleniumHQ/selenium/releases/tag/selenium-3.141.59

**Comment by chenrui333** [comment]
I will just update the PR to reflect the python update then. Thanks for the lightening turn-around. :)

**Comment by aaltat** [comment]
Thank you for the pull request.

**Pull request merged**
