### PR TITLE
Keyword Press Keys version 2 beta1. Please review code and tests.

### PR DESCRIPTION
**Pull request by HelioGuilherme66**
This is the proposed RC version, now with a clean PR from rtomac.
The way it is implemented does not allow to send a string of text. This will be fixed by adding a named argument (text=).
Still to decide if we will be using '+' or '-' as separator for special keys (for example SHIFT+a). Currently we can use either.

### CODE REVIEW

**Comment by pekkaklarck** [comment]
I consider the code too complicated. It also contains plain `expext:` and commented code. I'm still not sure about the design either. Using `+` around.BACKSPACE is just weird. We should agree on the design and fix `Press Key` broken by earlier changes before trying to write the code.

**Comment by HelioGuilherme66** [comment]
Now that I have a cleaned branch, I will work to improve the code and include the string fix.
I now see what you mean with +BACKSPACE, that would be an escaping mode. This will be cleared when we have the text=  argument. If is a single key just BACKSPACE, but if the user wants to press CONTROL+BACKSPACE it will work as expected (I think it will delete the word on the left of cursor). If the user wants to type BACKSPACE while pressing down a special key it would have to pass: CONTROL    text=BACKSPACE (a crazy user?). The same goes, for example with SHIFT+TAB to change back a field. Another good example is EMACS and CONTROL+x CONTROL+s. Currently we can just send CONTROL+xs, but it will be possible to send CONTROL    text=xs. (I don't like it).

**Comment by pekkaklarck** [comment]
In my opinion `CTRL+C` should mean pressing `C` while holding the control key. I'm not sure what `CTRL+AB` should do or should it be error, thoigh. We seriously need to design and agree on the usage first and implement this then. Should also take `Press Key` into account.

**Comment by Tset-Noitamotua** [comment]
May I give my five cents to this ;-)

``` python
def press_keys(self, locator, keys):
        """Simulates user pressing one or more KEY(s) or SPECIAL KEY(s) simultaniuosly or in sequence
        on element identified by `locator` while HOLDING DOWN one or more MODIFICATION KEY(s).

        `KEY`:                  0-9, aA-zZ, -+*/% etc.
        `SPECIAL KEY`:          F1-F12, DEL, TAB, ARROW_UP/_DOWN/_LEFT/_RIGHT etc.
        `MODIFICATION KEY`:     ALT, ALT_GR, CTRL, R_CTRL, SHIFT, ALT_SHIFT, ALT_GR_SHIFT etc.

        `KEY` is either a single character, (TODO: or a numerical ASCII code of the key lead by '\\\\'),
        or a sequence of single characters.
        `SPECIAL KEY` and `MODIFICATION KEY` are special key names defined at selenium.webdriver.common.keys.

        Examples:   # locator     # key sequence                # usage example
        | Press Keys | <locator> | CONTROL + a              | # select
        | Press Keys | <locator> | CONTROL + A              | # select
        | Press Keys | <locator> | CONTROL + A              | # select
        | Press Keys | <locator> | CONTROL + C              | # copy
        | Press Keys | <locator> | CONTROL + V              | # paste
        | Press Keys | <locator> | CONTROL + ABC            | # custom
        | Press Keys | <locator> | CONTROL + SHIFT + A      | # e.g. opens Firefox's Add-ons-Manager
        | Press Keys | <locator> | CONTROL + ALT + DELETE   | # e.g. shows lock screen on Windows
        | Press Keys | <locator> | CONTROL + ARROW_UP           | # and so on
        """

        keys =  keys.split(' + ')

        i = 0
        named_keys = []
        named_key_sequence = []
        unnamed = ''
        for key in keys:
            try:
                named_key = getattr(Keys, keys[i])
                print "%s. named key is %s." % (i + 1, key)
                named_keys.append(keys[i])
                i = i + 1
            except:
                print "The rest '%s' is unnamed." % key
                unnamed = str(key).lower()
                i = i + 1
        print "NAMED KEY(s):", named_keys
        for key in named_keys:
                named_key_sequence.append('Keys.%s' % key)
                named_key_seq_as_string = ','.join(named_key_sequence)
        print "NAMED KEY SEQUENCE:", named_key_sequence
        print "NAMED KEY SEQUENCE as STRING:", named_key_seq_as_string
        print "element.send_keys() call should look like this:"
        print "element.send_keys(%s, '%s')" % (named_key_seq_as_string, unnamed)

        #select it
        element = self._element_find(locator, True, True)
        # execute 'press_keys' action
        exec("element.send_keys(%s, '%s')" % (named_key_seq_as_string, unnamed))
```

Don´t judge me too hard, please ... I´m not a programmer :))) 
All the `print` statements are just for debugging, of course. And this is not thoroughly tested yet.

**Comment by just-be-dev** [comment]
I like it!

**Comment by Tset-Noitamotua** [comment]
Thanx!!! This makes me happy :-)

I already found some issues which I documented here: https://groups.google.com/forum/#!topic/robotframework-users/mHRq6o-T7a4

**Comment by aaltat** [comment]
Ugh

Pull request are welcomed:
https://help.github.com/articles/using-pull-requests/

-Tatu
Send from my mobile

**Comment by Tset-Noitamotua** [comment]
I don't know if I did it right but I did it ... I did a pull request :)))

**Comment by Tset-Noitamotua** [comment]
Design discussion continious in #498

**Comment by aaltat** [comment]
Closed. After #498 design is done we can make new pull request.

**Pull request closed without merging**
