### PR TITLE
Makes Selenium2Library compatible with both Python 3.4 and 2.7

### PR DESCRIPTION
**Pull request by HelioGuilherme66**
Tested in Linux x64.

### CODE REVIEW

**Comment by pekkaklarck** [comment]
If the idea is to keep the code base Python 2 compatible, using 2to3 is not a good idea. Converting code manually and using `future` or `six` as the compatibility layer works much better. For more details see e.g. http://python-future.org/. 

In my opinion we should first decide together what approach to use when porting. That covers deciding what compatibility layer to use (`future`, `six`, create own, Robot's `utils`) and do we want the code to look more like Python 2 or Python 3.

**Comment by HelioGuilherme66** [comment]
I did use `future` after analysis of Robot Framework code. The 2to3 converter surprised me for its efficiency, and I think is a very good starting point. I go now see why Travis is failing.

**Comment by HelioGuilherme66** [comment]
I fixed the problem. There is a launcher for testserver depending if we are on Python 2 or 3. (forgot to add the files). Now the Travis failing should be related with timeout when starting server (locally runs fine).

**Comment by pekkaklarck** [comment]
I totally disagree about 2to3. It has done lot of stupid changes to the code. I'm strongly -1 on using it. Much better do the conversion manually from the start than trying to fix mess 2to3 has created. Manually going through the code also makes it possible to enhance code otherwise. All that is going to help with future maintenance.

**Comment by aaltat** [comment]
Because many other projects have abandoned 2to3, for good reasons, I think we should not repeat their mistakes. Also I agree that code does not look good.

I have not read Robot `utils` code, but my first gut feeling would be to go with `future`. But because it's just a gut feeling, I don't feel strongly about it.

Because Python 3 is the future (on could even argue that it's a present), I think code must look like Python 3.

**Comment by pekkaklarck** [comment]
A big problem with using `robot.utils` as Python 2/3 compatibility layer is that it requires RF 3.0. I agree that `future` or a little more lower level `six` is a good choise.

**Comment by aaltat** [comment]
I think we should update the #479, when we agree on something. Also setting up CI to test against Python 3 would be good too. And dropping 2.6 would be nice too, in my personal opinion. I think we should have some sort of consensus, how we are going to do this.

**Comment by pekkaklarck** [comment]
Dropping Python 2.6 support is a good idea. It cost us way too many hours with RF 3.0.  RF 3.1 will drop it.

**Comment by HelioGuilherme66** [comment]
Closing in favor of #564 (better commits/PR changes).

**Pull request closed without merging**
