### PR TITLE
Added saucelabs config to travis

### PR DESCRIPTION
**Pull request by just-be-dev**
Related to #467, #383, and #247 

The start to adding sauce-labs to our CI process to get mutli-browser coverage.

### CODE REVIEW

**Comment by just-be-dev** [comment]
Argh. I've made progress, but it isn't quiet there yet. 

I believe I need to pass in the browser to desired capabilities now... but I can't pass in a dictionary through the command line so I don't think I can set that through `run_tests.py`. Even though I'm using 2.9rc1, I can't use the dictionary variable type because of backwards compatibility reasons... which makes me wonder what we'll do after that's deprecated... 

Anyway, I'm off to bed. If anyone feels like poking around on this PR and giving me hints, I'd appreciate it!

**Comment by markwinspear** [comment]
these can be set on the command line... -v DESIRED_CAPABILITIES =  name:Win8 + Chrome 43,platform:Windows 8.1,browserName:chrome,version:43
so in the CI server, if this is executed as a batch file, just have a number of jobs with varying desired capability strings.
This page generates required strings for the capabilities: https://docs.saucelabs.com/reference/platforms-configurator/

**Comment by just-be-dev** [comment]
As a note to myself in the future: Use [yaml variable files](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-file-as-yaml)!

**Comment by just-be-dev** [comment]
I'm no longer very active on this project and can't implement this feature.

**Pull request closed without merging**
