### PR TITLE
various small fixes (headers, caps, tabs, typo...)

### PR DESCRIPTION
**Pull request by laurentbristiel**

### CODE REVIEW

**Comment by ombre42** [comment]
I'm a little confused about this pull request. Robot Framework is executing our tests as intended, so I do not see how this fixes anything. You can use a single or multiple asterisks, "setting" or "settings", and for data separation, two spaces or four works just as well. This project does not have guidelines for test file syntax as far as I know. What value does this add to the project? I do not want to discourage you from contributing to this project, though. You contribute a lot to the community.

**Comment by laurentbristiel** [comment]
Agreed. Does not add value to the project. I was just reading the tests and made those small changes to be more homogeneous with what I see elsewhere in Robot Tests. If this adds more noise than signal to the project, I am fine with your rejecting the pull request.

**Comment by pekkaklarck** [comment]
Personally I value consistency pretty highly but agree that a precondition for that would be having guidelines. I hope I have time to write such guidelines to Robot Framework itself this autumn then other projects could refer to those guidelines if they wanted to.

A concrete reason why to use consistent headers is that some Robot plugins (at lest the PyCharm plugin I use) don't recognize all possible variations. That can be argued to be a bug in such plugins, though.

**Comment by ombre42** [comment]
When we implement #312 we could define standards and re-format as we rename.
Mainly my concern is there is a lot of impacting issues that were reported a long time ago and not yet fixed. Until the TODO list gets smaller, I do not want to worry about format issues.
We do not even have a coding format standard :)

**Comment by pekkaklarck** [comment]
@ombre42 Totally agreed, formatting changes to tests are good to be done if/when taking `*.robot` extension to use.

**Pull request closed without merging**
