### PR TITLE
Fixes installer for both Python 2.7 and 3.x.

### PR DESCRIPTION
**Pull request by HelioGuilherme66**
Replaces problematic execfile by exec.

### CODE REVIEW

**Comment by pekkaklarck** [comment]
Why would be `compile` needed here? AFAIK this ought to be enough:

```python
with open(join(CURDIR, 'src', 'Selenium2Library', 'version.py')) as f:
    exec(f.read())
```

**Comment by HelioGuilherme66** [comment]
Modified code as @pekkaklarck suggestion.

**Comment by aaltat** [comment]
Would you mind rebase with the current master. I would like to see that the change works with Python 2 and 3 with Travis.

**Comment by HelioGuilherme66** [comment]
Rebased (tests pass except on python 3.3).

**Pull request merged**
