### PR TITLE
Update PLC to 3.0.0

### LINKED ISSUE #1733: The Wait Until * keywords don't support a None value for the error parameter
## Steps to reproduce the issue

```
*** Settings ***
Library     SeleniumLibrary

*** Test Cases ***
Test
    Open Browser  url=https://github.com/  browser=Chrome

    Run Keyword And Expect Error        Element * not visible after *
            ...     Wait Until Element Is Visible    locator=xpath://div[@id="nosuchelement"]   timeout=200 milliseconds 

    # the previous call passes, the following - not:

    Run Keyword And Expect Error        Element * not visible after *
            ...     Wait Until Element Is Visible    locator=xpath://div[@id="nosuchelement"]   timeout=200 milliseconds     error=${None}
    # the failure is
    # Expected error 'Element * not visible after *' but got 'None'.

    [Teardown]      Close Browser
```
## Error messages and additional information

The issue is applicable to all `wait_until_*()` methods in the `keywords\waiting.py` file; apparently the type hinting makes Robot Framework itself to cast the value to str - once the value is passed as a method argument, it's already a string.

## Expected behavior and actual behavior

Passing a `${None}` argument to `error` should be equivalent as not setting a value at all, leaving it to default. But it's actually substituted with the string representation, e.g. `"None"`

## Attempted workarounds
Changing the hint to `Union[str, None]`, `Union[None, str]`  - no luck, still the same unexpected behavior.

## Environment

Browser: Not important (reproduced with Chrome v91.0.4472.77)
Browser driver: Not important (reproduced with chromedriver v91.0.4472.19)
Operating System: Win 10, AWS Linux, Ubuntu 18.04
Libraries
- Robot Framework: 4.0.3
- Selenium: 3.141.0
- SeleniumLibrary: 5.1.3
- Interpreter: py3.7.8

### PR DESCRIPTION
**Pull request by aaltat**
Fixes #1733

### CODE REVIEW

**Comment by emanlove** [comment]
@aaltat .. this is a very silly questions but making sure my thinking is correct .. anyone installing seleniumlibrary who has not pinned pythonlibcore has been installing 3.0.0 since Jun 11, 2021, correct?

**Comment by emanlove** [comment]
Ran against the latest set of tests and main branch code [here](https://github.com/emanlove/robotframework-seleniumlibrary/actions/runs/3212634583) with passing results.

**Comment by aaltat** [comment]
Should be correct at least with new installations people should get the latest PLC.

**Comment by emanlove** [comment]
For me it was a question of seeing the scope of affected code/functionality by this change and knowing how to test. It was tough for me to understand directly how this might affect the library. Having it out in the field for some time, to me, helps to shift testing from "knowing the code" to "experiencing the code".

Kiitos for the contribution! Merging into master ..

**Pull request merged**
