### PR TITLE
add keyword input_text_into_prompt

### PR DESCRIPTION
**Pull request by ghost**
add keyword input_text_into_prompt ( example from boakley )
fixes issue #292 "Add ability to type into a prompt"

### CODE REVIEW

**Comment by just-be-dev** [comment]
We seriously didn't already have this? 0.o

**Comment by just-be-dev** [comment]
Wow. Heh. Anyway, @ekasteel, it looks good to me. Can you add a test and update the changelog? Thanks!

**Comment by just-be-dev** [comment]
Could you merge in master? There was an error that was causing tests to fail, but it should be fixed now.

**Comment by ghost** [comment]
not sure what went wrong. things look messy, I do not want the commits for the test to be part of the pull request ( at least not until I am sure they work fine )

**Comment by just-be-dev** [comment]
It's not your changes that are failing, it's an issue with the newest version of selenium. Another PR already fixed the issue, so updating your PR should correct the tests.

**Comment by ghost** [comment]
the keyword now has a test which passes. looks fine to me
please note the example is from boakley and fixes issue #292 "Add ability to type into a prompt"

**Comment by just-be-dev** [comment]
Looks good! Would you mind updating the change log? After that I'll merge it in.

**Comment by ghost** [comment]
change log updated

**Comment by just-be-dev** [comment]
Thanks.

**Comment by zephraph** [comment]
For some reason your test is failing. 

Can you take a look at [this](https://travis-ci.org/rtomac/robotframework-selenium2library/jobs/72136796) and tell me if you can figure it out?

I'm in a rush and I'll have to revert your changes if I can't get it working soon. 

We're trying to push out a hotfix for the selenium upgrade issue.

**Comment by just-be-dev** [comment]
Could you take a look at this?

https://travis-ci.org/rtomac/robotframework-selenium2library/jobs/72146078

I'm going to revert your changes for now, they're holding up a hotfix that we have to get out. 

**Edit**: Unless I can figure them out pretty quickly. I'm going take another look at this after lunch.

**Comment by emanlove** [comment]
This error is not occurring on my machine (Linux / Firefox 23). Not saying that we are good to go just that I am not seeing the error. This doesn't surprise me as I have seen other system differences.

I will note that the test for this isn't actually verifying anything. It should check to see that the name shows up on the page (as the test page is currently coded). Also this should probably be a part of the acceptance.keywords.javascript test suite and not necessarily it's own.

**Comment by just-be-dev** [comment]
I'll make those changes. I think I fixed the error that Travis was running into.

**Pull request merged**
