### PR TITLE
Fixed documentation for custom locator example, so argument lines up with usage

### PR DESCRIPTION
**Pull request by DanielPBak**
Self-explanatory. The example here is incorrect, I have fixed it.

### CODE REVIEW

**Review by aaltat — CHANGES_REQUESTED** [review]
There is a bug in the documentation. I would actually change the `criteria` and `strategy` to `locator`. Please note that `strategy` is referenced at least once in the chapter and that actually should be changed also. Would you be willing to make this change?

**Comment by aaltat** [comment]
Thanks for pointing out the error. I did have an improvement idea, would you be willing to do what I did suggest in the comment?

**Comment by DanielPBak** [comment]
Sure!

**Comment by DanielPBak** [comment]
I have implemented the changes you requested :)

**Review by aaltat — COMMENTED** [review]
Also in here: https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py#L204 word strategy should be changed to locator.

**Comment by aaltat** [comment]
Sorry for the long delay. It looks ok in the example level, but you missed a word in few lines below. Could you fix that one too?

**Comment by aaltat** [comment]
Thanks for the contribution. If you want, you can add your name to: https://github.com/robotframework/SeleniumLibrary/blob/master/CHANGES.rst

**Comment by DanielPBak** [comment]
Sure! https://github.com/robotframework/SeleniumLibrary/pull/1178

**Pull request merged**
