### PR TITLE
Test with Python 3.6 instead of Python 3.3

### PR DESCRIPTION
**Pull request by cclauss**

### CODE REVIEW

**Comment by cclauss** [comment]
These changes solve several Python 3 issues but I can not determine how to fix the one failing test case: https://travis-ci.org/robotframework/Selenium2Library/jobs/220904266#L845

**Comment by HelioGuilherme66** [comment]
Please change your Git strategy. I recommend for you to:

1.  Set up your own Travis builder (it's free)
2.  Close this PR, and resubmit after doing all the testing and Squashing!

**Comment by cclauss** [comment]
Agreed.  The last successful build on this repo was your [Travis 816 build](https://travis-ci.org/robotframework/Selenium2Library/pull_requests) 3 months ago.

**Comment by aaltat** [comment]
Thank you for the effort. But it might have been good idea to discuss​about the problem first. We, here means maintainers, might have an opinion how that should have been fixed.

**Comment by pekkaklarck** [comment]
Notice also that Python 3 efforts, and any other larger change, should wait for the new architecture that is currently under review and finalization. See #770 for details.

**Pull request closed without merging**
