### PR TITLE
Fix deprecation warning switch_to_frame

### PR DESCRIPTION
**Pull request by ghost**
Fix deprecation warning switch_to_frame
since selenium release 2.41.0 this should be switch_to.frame

### CODE REVIEW

**Comment by aaltat** [comment]
Sorry for a long delay in the answer but are you interested to get this to the master? If you are this requires some thoughts.

1) Would you happen to remember, in which version the API was changed?
2) We support selenium starting from 2.32.0 and if the API was changed after version, we should not directly use the new API, instead we should do try/expect block and expect proper error.

**Comment by aaltat** [comment]
We are planning some architecture changes. This architecture change will most likely change the current code base in such way that the PR will cause conflicts and therefore cannot be merged directly to the master.

We don't have a excat date for the architecture change, but most likely it will happen in early next year. If you want this PR to be merged in the master before the architecture change, now is the time to improve the PR and get it merged to the master.

**Comment by ghost** [comment]
no, the changes are minor and can be redone after the architecture changes

**Comment by ghost** [comment]
Close pull request (not merged)

**Pull request closed without merging**
