### PR TITLE
run_tests.py cleanup

### PR DESCRIPTION
**Pull request by pekkaklarck**
- Use external robotstatuschecker module instead of our vendored copy
- Add docstring and use it in when showing usage on the cli
- Use rebot_cli for generating logs/reports instead of running rebot
  on the system
- General cleanup here and there

### CODE REVIEW

**Comment by aaltat** [comment]
Any idea why the robotstatuschecker was not installed by Travis?

**Comment by pekkaklarck** [comment]
I guess it should be in some Travis config? Updating them probably needs to wait for the CI enhancements PR to be merged first.

**Comment by aaltat** [comment]
The CI enhancement is now in the master and now use the requirements.txt and requirements-dev.txt files.

**Comment by pekkaklarck** [comment]
Merging latest run_tests.py changes turned out to be too complicated. Replaced this PR with PR #710.

**Pull request closed without merging**
