### PR TITLE
Configure Travis to get latest or pinned geckodriver, and set to test Firefox (or ESR) on PR and Cron.

### PR DESCRIPTION
**Pull request by HelioGuilherme66**
Added configuration for:
Python 2.7; RF 2.8.7 and Python 3.6; RF 3.0.2
Uses latest Firefox and geckodriver (current 52.0.2 and 0.18)
(Update) Commented the "latest" setup and set the "latest-esr" with geckodriver 0.16.1.
(it is difficult to know which version is for ff ESR 53)

Exposes 7 failed tests on both setups.

### CODE REVIEW

**Comment by HelioGuilherme66** [comment]
No more development on this PR.
Problems with Firefox/geckodriver:
- Double-click
- Close Browser

**Comment by aaltat** [comment]
I did run my test using FF 55.0.2 (64bit), selenium 3.5.0 and geckodriver 0.18.0. I di d also ran in to few failures in tests, which seemed problems with our test/code and one which could be problem with geckodriver or selenium. 

But I did not find any problems with closing the FF browser. What kind of problems you did find with closing the browser?

**Comment by HelioGuilherme66** [comment]
Got stuck sometimes with Webdriver Error. In Windows I had a lot of firefox windows open.
Now there are more fixes to exclude known issues. See PR #890 for a sucessful build on Travis with 14 failed tests.

**Comment by aaltat** [comment]
Could we have the changes in same PR? In this pre release phase, I would like to keep the build green. Also including the changes test case tags. For starters, could we aim for latest FF and geckodriver.

**Comment by HelioGuilherme66** [comment]
I will, then:
Use this PR to merge developments from #890,
Add more excludes for failed FF tests,
Give you Green light to merge, when all tests are Green ;)

**Comment by HelioGuilherme66** [comment]
Closing this, we can merge #890 all tests are green.

**Pull request closed without merging**
