### PR TITLE
Add support for parent element for ElementFinder and TableElementFinder to support normal locator strategies

### PR DESCRIPTION
**Pull request by aaltat**

### CODE REVIEW

**Comment by aaltat** [comment]
Things to do: 
- [x] Write better test in test_tableelementfinder.py test
- [x]  Make acceptance test to use newly supported locators like `id`, `name` and so on.

**Comment by pekkaklarck** [comment]
Test also new `strategy:value` syntax.

**Comment by aaltat** [comment]
The table element keyword are now done. I will fix the library documentation in separate PR.

**Comment by aaltat** [comment]
This fixes #923

**Comment by pekkaklarck** [comment]
So much better than it used to be! More functionality with less code (+281 additions, −293 removals) is always nice.

**Pull request merged**
