### PR TITLE
When screen shot is taken file is not overwritten

### PR DESCRIPTION
**Pull request by aaltat**
When screen shot is taken and if the file already exist, the file name is changed to contain -1 in
the end. Example foobar.png is changed to: foobar-1.png

### CODE REVIEW

**Comment by aaltat** [comment]
This pull request is same as #426 but all commits has been squashed to a single commit and it is has been merged with latest changes is with master.

**Comment by just-be-dev** [comment]
I'll look over this and test it sometime later this afternoon.

**Comment by just-be-dev** [comment]
@aaltat, I'm sorry for letting this issue float for so long!

I'll really make my best effort to look at it tonight. I've got to wade through this and see what effect the changes I made in #443 are.

**Comment by aaltat** [comment]
@zephraph No problem, this is open source and at least I am doing this for fun. So no stress

**Comment by just-be-dev** [comment]
:+1: It's the same for me, but I'll get to it as soon as I can.

**Comment by aaltat** [comment]
Now when 1.7.4 is out, what about this?

**Comment by just-be-dev** [comment]
We'll put it on the 1.8 milestone. There are some tweaks I'd like to make.

**Comment by aaltat** [comment]
And it seems to have some conflicts, I will sort those out

**Comment by aaltat** [comment]
Darn making that rebase in that way was not a good idea... Just re-writed the whole history.

OK, I will sort that out, but not tonight, need some sleep that do not anymore make anymore stupid mistakes.

**Comment by aaltat** [comment]
Hmm, perhaps it's easiest to make yet another pull request...

**Comment by aaltat** [comment]
Because I did screw up the history, created new pull request #501. Closing this on favor of #501

**Pull request closed without merging**
