### PR TITLE
add ability of embedding screenshots as base64 encoded images in the …

### PR DESCRIPTION
**Pull request by bitcoder**
implements #1483 as discussed.

Sum up of what's implemented:
- "Capture Page Screenshot" and "Capture Element Screenshot" will embed screenshots in the logs/reports in the following cases:

1. if screenshot_root_directory has been set as EMBED and no filename has been explicitly specified as argument to the previous keywords 
2. if filename has been explicitly specified as argument, with the value EMBED, in the previous keywords, independently of the screenshot_root_directory

Whenever embedded, screenshots are added using the  element and the "src" attribute with base64 encoded data in the log file. Screenshots are not saved as local files in this case.

### CODE REVIEW

**Comment by bitcoder** [comment]
pending rewriting some existing test scenarios and also fix on screenshots taken over elements

**Comment by aaltat** [comment]
Sorry for the delayed answer, but I have been busy in real life.

I thank you for your efforts, but your code is quite complicated. I have an idea how to make it more readable, but it means that you need to delete bunch of the existing code. Would you like to work with the PR and with me, to improve the PR?

**Comment by bitcoder** [comment]
Hi @aaltat , sure. How do you want to move forward?

**Comment by aaltat** [comment]
Well, perhaps we should discuss first. Are you in Robot Framework Slack and can we find time which is suitable for both of us? I am in GMT+2 and can arrange example 30mins almost any in  time of day.

**Comment by aaltat** [comment]
I did read the code and I did do some experimenting in the side, to learn few things that where unknown for me and to be able to provide better feedback for your PR. I was carried away with the experimenting and after while I did notice that I had working code in a branch which was only missing the documentation. Therefore I created #1518 and I am going to close this in favour of #1518 

I do want to thank you for giving good ideas how this could be implemented and on the initial work how the Base64 encoded image can be embedded in the log.html.

**Pull request closed without merging**
