### PR TITLE
Updated documentation for locators

### PR DESCRIPTION
**Pull request by aaltat**
Also mentions that xpath is supported without using the xpath prefix.

### CODE REVIEW

**Comment by aaltat** [comment]
Also added acceptance tests.

**Comment by pekkaklarck** [comment]
Doc changes look great. Should mention that `(//` is supported only by next version, though, but the problem is specifying what version and library name to use. SL will be 3.0, but should S2L be 3.0 or 2.0? If both are 3.0, we could say "supported by library version 3.0 or newer" or something similar.

**Comment by aaltat** [comment]
Perhaps we create SL and S2L as 3,0? It would solve the problem nicely.

**Comment by pekkaklarck** [comment]
Yeah, v. 3.0 with both sounds good to me.

**Pull request merged**
