### PR TITLE
Add 'Element Should Not Contain' keyword

### PR DESCRIPTION
**Pull request by molsky**

### CODE REVIEW

**Comment by molsky** [comment]
Changed variable name `text` back to `expected`.

**Comment by molsky** [comment]
Any news about this one?

**Comment by just-be-dev** [comment]
I'm re-running the tests. If they fail again it's just a matter of figuring out why it failed and how to fix it.

**Comment by just-be-dev** [comment]
Hey @molsky, it looks like you need to rebase.

**Comment by molsky** [comment]
Rebased.

**Comment by just-be-dev** [comment]
One last thing @molsky. Would you update the changelog as well?

**Comment by molsky** [comment]
Updated changelog for this pull request.

**Comment by just-be-dev** [comment]
Cool. Thanks for the update!

**Pull request merged**
