### PR TITLE
Added Safari browser support.

### PR DESCRIPTION
**Pull request by emanlove**

### CODE REVIEW

**Comment by zmlpjuran** [comment]
I'm curious how adding safari can affect Firefox Click Element At Coordinates test.

**Comment by emanlove** [comment]
@zmlpjuran: It should pass as long as native events are working with Safari.

**Comment by zmlpjuran** [comment]
@emanlove: I meant the Travis CI report for your commit, but then I observed that tests continuously fails from previous commits

**Comment by j1z0** [comment]
Yeah safari doesn't have anything to do with it.  It's a bug in FF webdriver. We just need to keep our test suite up to date. 

Cheers,
Jeremy

**Comment by praduman** [comment]
How to use safari browser. Do we need any driver for that.

**Comment by zmlpjuran** [comment]
You need only python selenium2 library which is installed as dependency by default. For sophisticated deployment you can use selenium grid.

**Comment by ezTestAutomation** [comment]
Drag and Drop keyword does not work on Safari. When running it raises error Unknown command: mouseMoveTo (WARNING: The server did not provide any stacktrace information). Could you please let me know if there is any solution on this issue?. Thanks

**Comment by zmlpjuran** [comment]
tusoi: Hi, this is known limitation of Safari driver, it is nothing that can be fixed on selenium2library as it is like "proxy" interpreter.
see http://code.google.com/p/selenium/issues/detail?id=4136 and star it to fix it soon

**Comment by CMTaylor** [comment]
This enhancement for Safari support doesn't seem to have made it to a release of Seleniu2Library yet. When is the next release planned? I'd really like to use this new feature!

**Pull request merged**
