### PR TITLE
Reverted press key changes

### PR DESCRIPTION
**Pull request by just-be-dev**
Completely reverted press key changes to how it was in 1.7.2.

### CODE REVIEW

**Comment by just-be-dev** [comment]
@emanlove, @pekkaklarck, @aaltat 

Could any of you take a look at this? Feel free to test it as well. 

This is essentially a direct copy of what 1.7.2 had for this keyword.

**Comment by pekkaklarck** [comment]
Using a direct copy of 1.7.2 version is fine. It would be a good idea to enhance docs to explain that multiple chars work too and add a test for the functionality. That should probably be a separate issue, though.

**Comment by aaltat** [comment]
For my eyes it looks good. Code is more or less identical with 1.7.2, only few comments are missing. And the comments are only commenting out old code, so we are better not to have it in.

**Comment by just-be-dev** [comment]
Yeah, I removed the commented out code intentionally, other than that it's exactly like 1.7.2. I did do another PR to add tests/documentation for the string support. That's all been released now in 1.7.4.

**Pull request merged**
