### PR TITLE
Added method to find element by class name #673

### PR DESCRIPTION
**Pull request by Gaurang033**
Added a new locator strategy find by class name and unit test case for it.

### CODE REVIEW

**Comment by aaltat** [comment]
I did restart the Travis build because it seems that the error is not related to your chances.

PR must also update the library documentation in here https://github.com/robotframework/Selenium2Library/blob/master/src/Selenium2Library/__init__.py Update the chapter which describes the locator strategies.

Usually it would be good idea to write acceptance test also. It would help to detect if the selenium interface changes.

**Comment by aaltat** [comment]
The Travis build did fail again. Would you mind looking what the actual failure seems to be?

**Comment by Gaurang033** [comment]
Hi,

I just checked the logs, it seems like geckodriver execute path is not set,
Following is the error message. All the tests are passing locally.
WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

**Comment by aaltat** [comment]
Oh darn. In that case it seems that Travis did update the Firefox to a version which needs the geckodriver. Therefore it needs some work from the admin side. Have to take a look and fix it asp. Let's see can I find time later today.

**Comment by HelioGuilherme66** [comment]
@aaltat I have already fixed Travis build. I have restarted the build of this PR.

**Comment by aaltat** [comment]
The pull request needs to rebased locally with master and push again to upstream.

**Pull request merged**
