### PR TITLE
method input_password() docstring has been supplemented.

### PR DESCRIPTION
**Pull request by stasiek**
Since it's a known issue ( https://github.com/rtomac/robotframework-selenium2library/issues/202 ) it should at least be mentioned in the docstring.

### CODE REVIEW

**Comment by emanlove** [comment]
I agree this should be in the docstring but you should clarify under which scenarios it shows up, that is when using loglevel DEBUG. Otherwise it is confusing to say "it does not log it" but than say "it is in the report file" as those statements seem contradictory.

**Comment by aaltat** [comment]
We are planning some architecture changes. This architecture change will most likely change the current code base in such way that the PR will cause conflicts and therefore cannot be merged directly to the master.

We don't have a excat date for the architecture change, but most likely it will happen in early next year. If you want this PR to be merged in the master before the architecture change, now is the time to improve the PR and get it merged to the master.

**Comment by aaltat** [comment]
This is closed because of #984

**Comment by pekkaklarck** [comment]
More precisely commit 550ebaa.

**Pull request closed without merging**
