### PR TITLE
Fix s2l timeout bug

### PR DESCRIPTION
**Pull request by emanlove**
Added test code and bug fixes to resolve issue with set_selenium_timeout not passing timeout variable to selenium.  Also added execute asynchronous javascript keyword.

### CODE REVIEW

**Comment by j1z0** [comment]
fixed in the implicit wait branch and already merged

**Comment by emanlove** [comment]
On 01/17/2012 03:45 AM, Jeremy Johnson wrote:

> fixed in the implicit wait branch and already merged
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/rtomac/robotframework-selenium2library/pull/22#issuecomment-3524864

Jeremy,

I was reviewing these changes and realized that they are not in the 
implicit wait code.  These changes touch the timeout only and add both 
additional testing for the timeout as well as new functionality for 
asynchronous javascript through Selenium.  The reason I added async 
javascript keywords into rf-s2l was that, AFAICT, Selenium timeout is 
used only for these asynchronous javacript calls and no where else.  So 
these changes both fix a (still existing) bug where setting the timeout 
value within rf-s2l never passes it value to Selenium and adds the 
keyword to take full advantage of these timeout functionality.

I would have reopened the pull request but apparently not being a team 
member of rtomac/robotframework-selenium2library prevents me from doing 
so. Also I did push a minor change to my fix-s2l-timeout-bug branch 
correcting my sloppiness with the added newline within 
../keywords/_javascript.py so I would expect this to show up if this 
pull request is reopened.  Or I could just resubmit if you think that is 
better?

Ed

**Comment by j1z0** [comment]
Hey Ed,

OK sorry I missed that was just going on your comments when I closed the pull request, didn't even look at it.   I'll reopen it... Sorry for the general lack of response last week, I've got a bit deadline next Wednesday so it's kind of all out for me right now.  So it will probably be after that before I can update these things.  But just wanted to let you know I haven't forgotten.

Cheers,
Jeremy

**Comment by emanlove** [comment]
Jeremy,

Thanks for the note.  I understand as have been busy too. Have a good day.

Ed

**Comment by j1z0** [comment]
ok as per our email trail Ed I've reopened the pull request

**Pull request merged**
