### PR TITLE
Remove deprecated attributes

### PR DESCRIPTION
**Pull request by mihaiparvu**
PR for #1346.

### CODE REVIEW

**Comment by aaltat** [comment]
In same go, we could remove the also methods and attributes usgin `warnings.warn`. Mostly things explained in here:  https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/__init__.py#L652

**Comment by mihaiparvu** [comment]
Due to recent removals, the class `Deprecated` from [utils/deprecated.py](https://github.com/robotframework/SeleniumLibrary/blob/master/src/SeleniumLibrary/utils/deprecated.py) is left unused. Should I delete it or keep it for future deprecations?

**Comment by aaltat** [comment]
Ah, I did not remember that. If it is not used, then it can be removed.

**Comment by aaltat** [comment]
Thank you for the pull request.

**Pull request merged**
