### PR TITLE
Reverts Press Key to use double escaped Named keys.

### LINKED ISSUE #489: Press Key keyword no longer works with strings
Following example results in error (actual variable names replaced):

Press Key    ${EnterSomething}    test-something

This will error with message: ValueError: Unknown key named 'test-something'

### PR DESCRIPTION
**Pull request by HelioGuilherme66**
Fixes #489.

### CODE REVIEW

**Comment by just-be-dev** [comment]
Was the escaped name keys in there before your changes?

**Comment by HelioGuilherme66** [comment]
I think is was not added before. It was originated by this issue #275.

**Comment by aaltat** [comment]
If there are lot of commits, which needs to reverted and there are less commits that we want to the new release. Perhaps it is easiest to checkout the 1.7.2 tag, cherry pick the commits that we want and leave others out and make new release. 

Or if the pull request #474 is the only one that we need to revert, then lets revert only that one and make a new release.

**Comment by just-be-dev** [comment]
I think we need to roll back the changes all the way to 1.7.2 as @aaltat was suggesting. What about #494?.

**Comment by aaltat** [comment]
After the revert, how does the git log looks like? I am not sure how github does it, but I would aim to a method which:
1) Does the revert with less pain
2) We can be sure that revert did the thing it should have been doing. 
3) Clean commit history (optional)

I can review for #494 and try to see, does it solve the problem. I am busy with next few days, but on Friday, I should have some time to spare. But also it would be really nice if someone else would also take a look.

**Comment by HelioGuilherme66** [comment]
My revert PR is a cherry-pick only for the Press Key keyword. Let me add that the acceptance test passed also in Windows with IE 11.

**Comment by just-be-dev** [comment]
I didn't revert a commit so much as make a new commit with the contents of what 1.7.2 had. This is one of those issues where squashing would've been immensely helpful, but we didn't do it. Lesson learned.

**Comment by just-be-dev** [comment]
I'm going to close this for now. We'll create an issue on how to approach this in 1.8.

**Pull request closed without merging**
