### PR TITLE
Add ability to pass custom capabilities to local browsers

### PR DESCRIPTION
**Pull request by drobota**
Issue #550

### CODE REVIEW

**Comment by drobota** [comment]
@HelioGuilherme66  Can you have a look, please?

**Comment by HelioGuilherme66** [comment]
Looks good to me.
Run all tests under Linux with Firefox and Chrome.

**Comment by aaltat** [comment]
It would be good to write some tests to ensure that it works now and in the future.

**Comment by drobota** [comment]
@aaltat I added tests not for browser however they cover all my changes. Can you have a look? Thanks

**Comment by aaltat** [comment]
We are planning some architecture changes. This architecture change will most likely change the current code base in such way that the PR will cause conflicts and therefore cannot be merged directly to the master.

We don't have a excat date for the architecture change, but most likely it will happen in early next year. If you want this PR to be merged in the master before the architecture change, now is the time to improve the PR and get it merged to the master.

**Comment by aaltat** [comment]
Closing due inactivity. If you want to work on the matter, please create a new pr.

**Pull request closed without merging**
