### PR TITLE
fix `StringIO` import as it was removed in robot 5.0

### LINKED ISSUE #1752: support robot 5.0
```py
import SeleniumLibrary
```
```
(.venv) C:\Users\user\project>c:/Users/user/project/.venv/Scripts/python.exe c:/Users/user/project/Sandpit/test.py
Traceback (most recent call last):
  File "c:\Users\user\project\Sandpit\test.py", line 52, in <module>
    import SeleniumLibrary
  File "c:\Users\user\project\.venv\lib\site-packages\SeleniumLibrary\__init__.py", line 33, in <module>
    from SeleniumLibrary.keywords import (
  File "c:\Users\user\project\.venv\lib\site-packages\SeleniumLibrary\keywords\__init__.py", line 18, in <module>
    from .browsermanagement import BrowserManagementKeywords  # noqa
  File "c:\Users\user\project\.venv\lib\site-packages\SeleniumLibrary\keywords\browsermanagement.py", line 30, in <module>
    from .webdrivertools import WebDriverCreator
  File "c:\Users\user\project\.venv\lib\site-packages\SeleniumLibrary\keywords\webdrivertools\__init__.py", line 17, in <module>
    from .webdrivertools import WebDriverCreator  # noqa
  File "c:\Users\user\project\.venv\lib\site-packages\SeleniumLibrary\keywords\webdrivertools\webdrivertools.py", line 25, in <module>
    from robot.utils import ConnectionCache, StringIO
ImportError: cannot import name 'StringIO' from 'robot.utils' (c:\Users\user\project\.venv\lib\site-packages\robot\utils\__init__.py)
```

my understanding is that `StringIO` has been removed in 5.0 https://github.com/robotframework/robotframework/issues/4150

### PR DESCRIPTION
**Pull request by DetachHead**
fixes #1752

### CODE REVIEW

**Comment by DetachHead** [comment]
Assuming the failed CI has nothing to do with my change because the same is happening on every other open PR

**Comment by aaltat** [comment]
It's not, this is caused by a bug in ApprovalTests.Python.

**Comment by aaltat** [comment]
Ping @emanlove and @rasjani Approval test is causing problems, because of: https://github.com/approvals/ApprovalTests.Python/issues/103 

Pinning the Approval test version should fix the problem.

**Comment by emanlove** [comment]
Just an update, in adding robotframework version 5.0.1 the acceptance tests were having some strange issues. Investigated those last weekend with no resolution and ran out of time. Going to pick this back up again. Either way this changes looks needed so I am going ahead and merge it in. This may break tests for a bit.

**Pull request merged**
