### PR TITLE
prep for 1.7.3 release

### PR DESCRIPTION
**Pull request by just-be-dev**

### CODE REVIEW

**Comment by just-be-dev** [comment]
Resolves #476.

**Comment by just-be-dev** [comment]
See my comments on 29899a0 for why I added the keyword documentation back to the repository.

**Comment by just-be-dev** [comment]
@emanlove Are you good with this release? If so I'll try to push it out tonight.

**Comment by just-be-dev** [comment]
@pekkaklarck, can you look at this too?

**Comment by pekkaklarck** [comment]
Anything special you'd like me to look at?

**Comment by just-be-dev** [comment]
Nope, just a general review. I wanted someone else's ok before I pushed out a release.

**Comment by emanlove** [comment]
Sorry, I've been offline on vacation this past week. Thanks @zephraph for making this release!

**Comment by just-be-dev** [comment]
No problem!

**Pull request merged**
