### PR TITLE
 fix for deprecation warning for select_frame / unselect_frame #592 

### PR DESCRIPTION
**Pull request by ghost**
fix for deprecation warning for select_frame / unselect_frame #592

### CODE REVIEW

**Comment by ghost** [comment]
Apparently the current master branch has 2 errors and 3 warnings for unrelated tests ( these test also fail without this fix / pull request )

**Comment by aaltat** [comment]
Thank you from the pull request. The S2L minimum required selenium version is quite low and could you check if it needs raising? If needs to be raised we need provide some warning to the users and perhaps decide when this would be best to be done.

**Comment by ghost** [comment]
The deprecation change for selenium is in commit " lukeis committed on 19 Mar 2014 "
https://github.com/SeleniumHQ/selenium/commit/8fc478b09ea3c76800d09ab6681f9c3895b1bbc4

the first selenium release after that commit is 2.41.0 ( 23 march 2014 ) so that will be the version to use ( instead of 2.32.0 ).  I assume in the meantime most of us have upgraded ( it;s 2 years ago ).

**Comment by aaltat** [comment]
@emanlove what you think, should we raise the minimum required of selenium? Or should we make a try\cathc?

**Comment by ghost** [comment]
I would like to redo this pull request on a different branch ( not on ekasteel:master )

**Comment by emanlove** [comment]
I'll look to see if there is another pull request as @ekasteel noted, but I would prefer a try-catch block over updating the selenium version. In addition we could provide a warning about eventual need to upgrade.

**Comment by ghost** [comment]
the new pull request is #599...

**Pull request closed without merging**
