### PR TITLE
Drop support for Python 2.7 and 3.4

### LINKED ISSUE #1409: Drop Python 3.4 support in SeleniumLibrary 4.1
Python 3.4 is [end of life](https://www.python.org/dev/peps/pep-0429/) and we should remove support for it. Mainly this mean that we update Travis to test with Python 3.5. Inform community also about the decision.

### LINKED ISSUE #1444: Drop Python 2 support
Things to do:

- [x] Start support branch from latest release version and configure Travis to run it.
- [x] Clean CI so that it runs only with Python 3
- [x] Update Travis image to bionic
- [x] Clean unit tests that skip tests with Jython
- [x] Read code and see can something be improved. At least remove all PY2 and PY3 imports.
- [x] Take a peek in the acceptance test and is there something because of Python 2

By bye Python 2, it was a fun ride and welcome the new king Python 3: https://www.python.org/doc/sunset-python-2/

### PR DESCRIPTION
**Pull request by hugovk**
Fixes https://github.com/robotframework/SeleniumLibrary/issues/1444.
Fixes https://github.com/robotframework/SeleniumLibrary/issues/1409.

### CODE REVIEW

**Comment by aaltat** [comment]
Thanks you for the hard work, I really appreciate it. But the Python 2 support is dropped earliest at 1.1. 2020 and therefore I am unable to merge the PR for a long time.

**Comment by hugovk** [comment]
That's fine! Feel free to keep the PR until then or close it if you prefer.

How about a separate PR to drop 3.4? That's been EOL for several months already.

**Comment by aaltat** [comment]
Most likely I will modify the `setup.py` and mention it in the release notes. I will not force anything.

**Comment by aaltat** [comment]
Thank you for the pull request, it gave nice ideas how to enhance the library and I have copied needed parts to master. Therefore I am going to close this PR.

**Comment by hugovk** [comment]
👍

**Pull request closed without merging**
