### PR TITLE
line 67 changed because of issue "Keyword 'Capture Page Screenshot' coul...

### PR DESCRIPTION
**Pull request by hali4ka**
...d not be run on failure: AttributeError: 'WebDriver' object has no attribute '_execute'".

### CODE REVIEW

**Comment by hali4ka** [comment]
update regarding error in IE and Chrome

**Comment by adwu73** [comment]
Tried the modification on IE8 Win 7 with no luck

16:08:51.268 DEBUG Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\robot\running\timeouts.py", line 85, in run
    return runner.get_result()
  File "C:\Python27\lib\site-packages\robot\utils\robotthread.py", line 37, in run
    self._result = self._runnable()
  File "C:\Python27\lib\site-packages\robot\utils\robotthread.py", line 28, in <lambda>
    self._runnable = lambda: runnable(_(args or ()), *_(kwargs or {}))
  File "<string>", line 2, in capture_page_screenshot
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords\keywordgroup.py", line 12, in _run_on_failure_decorator
    return method(_args, *_kwargs)
  File "C:\Python27\lib\site-packages\Selenium2Library\keywords_screenshot.py", line 27, in capture_page_screenshot
    self._current_browser().save_screenshot(path)
  File "C:\Python27\lib\site-packages\Selenium2Library\lib\selenium-2.8.1\py\selenium\webdriver\ie\webdriver.py", line 71, in save_screenshot
    png = RemoteWebDriver._execute(Command.SCREENSHOT)['value']

**Comment by adwu73** [comment]
I tested this on IE8, Win 7 . It works, tks!!!

**Comment by j1z0** [comment]
Hey Steve,

Yes in fact if you go to the chrome web driver page this issue has been raised there.  Apparently it is fixed in the current development version of chrome.  So you might want to upgrade your chrome browser.  Anyways I'm closing this issue as it's clearly a chromedriver issue and not a s2l issue.

**Comment by docent** [comment]
I get the same behavior in IE9

**Pull request closed without merging**
