### PR TITLE
select content with mouse

### PR DESCRIPTION
**Pull request by gotcha**
This branch is not ready for merge.

I am a new contributor. Would you mind reviewing what has been done and giving me feedback ?

Thanks

### CODE REVIEW

**Comment by HelioGuilherme66** [comment]
You should add tests for the keyword, either in a new .robot file or in a suitable existing one. This way you should have tested them before committing the PR and helps everyone to validate the functionality.

**Comment by aaltat** [comment]
Although the Robot Framework [CONTRIBUTING.rst Code Contributions](https://github.com/robotframework/robotframework/blob/master/CONTRIBUTING.rst#code-contributions) is not officially ours, it offers good base. Also our [BUILD.rst](https://github.com/robotframework/Selenium2Library/blob/master/BUILD.rst) offers some but not all required information. Personal note: We should really fix the #485 

In nut shell: 
- Make also an issue 
  - It makes tracking the feature easier and consolidates the discussion to one place. 
  - Try to also write/describe what you want in general level in the issue.
  - Describing the acceptance tests, at least one or two, is also good idea. Because there rarely is so simple issue which could not be understated incorrectly.
- Make pull request
  - Tests are required. 
  - Following PEP-8 is required.
  - Wait for review and fix the comments. This part is usually repeated many times. 
  - If accepted, someone from core team will merge your pull request to the master

**Comment by aaltat** [comment]
We are planning some architecture changes. This architecture change will most likely change the current code base in such way that the PR will cause conflicts and therefore cannot be merged directly to the master.

We don't have a excat date for the architecture change, but most likely it will happen in early next year. If you want this PR to be merged in the master before the architecture change, now is the time to improve the PR and get it merged to the master.

**Comment by vairamsvsjdo** [comment]
@aaltat  WIth architecture change merged, can this take a second look. I understand it is missing tests.

**Comment by aaltat** [comment]
Closing due inactivity.

**Pull request closed without merging**
